version: '2'
services:
  data:
    image: alpine
    volumes:
      - ./backend:/home/booking/backend
    entrypoint: tail -f /dev/null

  backend:
    build:
      context: ./backend
    ports:
      - 127.0.0.1:4000:4000
    volumes_from:
      - data
