version: '2'
services:
  # Backend
  data_backend:
    image: alpine
    volumes:
      - ./backend:/home/booking/backend
    entrypoint: tail -f /dev/null

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  backend:
    build:
      context: ./backend
    ports:
      - 127.0.0.1:4000:4000
    volumes_from:
      - data_backend
    links:
      - mongodb

  # Frontend
  data_frontend:
    image: alpine
    volumes:
      - ./frontend:/usr/local/apache2/htdocs
    entrypoint: tail -f /dev/null

  apache:
    image: httpd:latest
    volumes_from:
      - data_frontend
    links:
      - backend
    ports:
      - "8080:80"

